apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: czcq
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: czcq
    app.kubernetes.io/part-of: byoc-app-bdez
  name: czcq
spec:
  rules:
  - host: czcq-byoc-tffi-tenant.apps.9b814fa5ab9139b71dd4.hypershift.aws-2.ci.openshift.org
    http:
      paths:
      - backend:
          service:
            name: czcq
            port:
              number: 8081
        path: /
        pathType: ImplementationSpecific
status:
  loadBalancer: {}
